[package]
name = "granular"
version = "0.1.0"
edition = "2021"

[dependencies]
granular-core = {path = "granular-core"}
geese.workspace = true
winit.workspace = true
env_logger.workspace = true
log.workspace = true
pollster = "0.3.0"

[workspace]
members = ["granular-core"]

[workspace.dependencies]
geese = "0.3.7"
env_logger = "0.10.1"
log = "0.4.20"
winit = { git = "https://github.com/rust-windowing/winit/", features = [ "android-native-activity" ] }
