[package]
name = "testbed"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
granular = { path = "../.." }

log.workspace = true
geese.workspace = true
palette.workspace = true
web-time.workspace = true
winit.workspace = true

fern = { version = "0.7.1", features = ["colored"] }
regex = "1.10.3"
glam = { version = "0.25.0", features = ["approx"] }
chrono = "0.4.45"

[features]
trace = ["granular/trace"]


[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "1.0"
wasm-bindgen = "0.2.127"
console_error_panic_hook = "0.1.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
humantime = "2.4.0"
