[package]
name = "simulation"
version = "0.1.0"
edition = "2024"

[features]
default = []
trace = [
    "dep:tracy-client",
    "dep:wgpu-profiler",
    "profiling/profile-with-tracy",
]

[dependencies]
granular-core = { path = "../granular-core" }
include-wgsl-oil.workspace = true
encase.workspace = true
wgpu.workspace = true
glam.workspace = true
web-time.workspace = true
bytemuck.workspace = true
palette.workspace = true

# Profiling
profiling.workspace = true


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Profiling
wgpu-profiler = { workspace = true, optional = true }
tracy-client = { workspace = true, optional = true }
