[package]
name = "granular-core"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
trace = [
    "dep:tracy-client",
    "dep:wgpu-profiler",
    "profiling/profile-with-tracy",
]

[dependencies]
geese.workspace = true
wgpu.workspace = true
winit.workspace = true
log.workspace = true
palette.workspace = true
web-time.workspace = true
bytemuck = "1.14.0"
bytemuck_derive = "1.5.0"
image = "0.24.8"
rustc-hash = "1.1.0"
anyhow = "1.0.79"
glam = { version = "0.25.0", features = ["approx", "bytemuck"] }
pollster = "0.3.0"
rayon = "1.11"
# Profiling
profiling.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notify = "6.1.1"
# Profiling
wgpu-profiler = { workspace = true, optional = true }
tracy-client = { workspace = true, optional = true }


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.123"
wasm-bindgen-futures = "0.4.73"
web-sys = { version = "0.3.100", features = [
    "console",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Location",
    "Window",
] }
